services:
  - type: web
    name: resume-ai-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      # Ensure Git LFS files are fetched in Render build environment
      curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      sudo apt-get update && sudo apt-get install -y git-lfs
      git lfs install
      git lfs pull
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

